### ISSUE TITLE
Method callReadTrxS2S

### ISSUE THREAD

**Issue by aalmagio** [gestpay/php5-gestpay-s2s#1]
In callReadTrxS2S.php, on line 50 there's an error: shoptransactionId should be shopTransactionId

**Comment by musikele** [comment]
Hi, thanks for reporting this bug. It will be fixed super-soon

**Comment by musikele** [comment]
Issue fixed with commit https://github.com/gestpay/php5-gestpay-s2s/commit/b5abe4604e0003ccb164bb777f04a7ce84c62591
